# This is a basic workflow to help you get started with Actions

name: On push to Main branch
# Controls when the workflow will run -- define the event or events
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  # push:
  # branches: [ "develop" ]
  # pull_request:
  # branches: [ "develop" ]
  [push, workflow_dispatch]
  # Allows you to run this workflow manually from the Actions tab
env:
  SECRET_EXAMPLE: ${{ secrets.SECRET_EXAMPLE }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"

  example:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # we use "uses" to call other actions, for more advanced usage you can use the word "with"
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "EXAMPLE: ${{ secrets.SECRET_EXAMPLE }}"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # we use "uses" to call other actions, for more advanced usage you can use the word "with"
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      # Installs latest version of nodejs
      - name: "Install NodeJs"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Install dependencies - ci and install are the same
      - name: Install dependencies
        run: npm ci
      # Runs tests
      - name: Run tests
        run: npm test
  deploy:
    # We added needs, because we want it sequential
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Install NodeJs"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Install dependencies - ci and install are the same
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
      #Artifact allow us to download code:
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build
